/* This file is automatically generated. DO NOT EDIT! */

#ifndef _fdprep_h
#define _fdprep_h


void fdprep(const double omega,
	    const float eps,
	    const int n1, const int n2,
	    const float d1, const float d2,
	    float **v,
	    const int npml,
	    const int pad1, const int pad2,
	    SuiteSparse_long n, SuiteSparse_long nz,
	    SuiteSparse_long *Ti, SuiteSparse_long *Tj,
	    double* Tx, double *Tz);
/*< 5-point finite-difference scheme >*/


void fdpad(const int npml,
	   const int pad1, const int pad2,
	   sf_complex **dat,
	   double *Bx, double *Bz);
/*< pad >*/


void fdcut(const int npml,
	   const int pad1, const int pad2,
	   sf_complex **dat,
	   double *Xx, double *Xz);
/*< cut >*/

#endif
