from rsf.proj import *
from rsf.recipes import fdmod
import slides_fig 

par = {'ox':0,'dx':1,'nx':512,'labelx':'x',
       'oz':0,'dz':1,'nz':512,'labelz':'z'}

fdmod.param(par)


# Download data
Fetch('mona.img','imgs')
# Convert to standard format
Flow('mona','mona.img',
     '''
     echo n1=512 n2=513 in=$SOURCE data_format=native_uchar |
     dd type=float|transp|window n1=512
     ''',stdin=0)




for ratios in ['4:3','16:9']:
  rname = '-'+ratios.replace(":","to")

  slide = slides_fig.slideFig(par,ratio=ratios,font=20,labelfat=2) #init object
  slide.print_dimensions()

  Result('mona'+rname,'mona',fdmod.cgrey('',par))
  
  for scales in range(20,121,10):
    scalar=scales/100
    Result('mona%d'%scales+rname,'mona',slide.cgrey('',scalar=scalar))

  Plot('monaMaxH'+rname,'mona',slide.vcgrey('',scalar=1))


fdmod.point('eye',200,150,par)

Plot('ss70-16to9','eye',slide.ssplot('',scalar=1))

Result('monaMaxH-16to9',['monaMaxH-16to9','ss70-16to9'],'Overlay')

for rule in range(20,41,2):
  ken = '-ken%02d'%rule
  slide = slides_fig.slideFig(par,ratio='16:9',font=rule) #init object
  Result('mona40-16to9'+ken,'mona',slide.cgrey('',scalar=.40))  
  
End()
