from rsf.proj import *
# Used to build all Java Mains, programs that do not belong to java packages
directories = \
'''
ediaz
'''


dirs = directories.split()
srcdirs = map(lambda x: 'src/'+x,dirs)

print project['ENV']
project.Java('bin',srcdirs,JAVACFLAGS='-source 1.5 -nowarn')
map(lambda x,y: project.Jar('jar/'+x+'.jar',y), dirs,srcdirs)

